<dialog id="info__ventana" class="info__ventana">
    <div class="container__info__ventana">
        <div class="info__ventana__title">
            <h3>¿C&oacute;mo cumplimentar el formulario?</h3>
            <p>Para poder tener una cuenta ClickByte y disfrutar de nuestros
                descuentos, le rogamos que lea la siguiente
                informaci&oacute;n:</p>
        </div>
        <div class="info__ventana__body">
            <p>
                <strong><span class="material-icons"
                              style="font-size: 18px; margin-right: 5px; color: var(--color-title);">verified</span>Todos
                    los campos
                    son
                    requeridos.</strong>
            </p>
            <p>
                <strong><span class="material-icons"
                              style="font-size: 18px; margin-right: 5px; color: var(--color-title);">verified</span>@Email:</strong>
                No le ser&aacute; posible
                introducir un correo electr&oacute;nico ya
                asociado a una cuenta.
            </p>
            <p>
                <strong><span class="material-icons"
                              style="height: fit-content; font-size: 18px; margin-right: 5px; color: var(--color-title);">verified</span>DNI:</strong>
                No
                le ser&aacute; posible
                introducir la letra. No se preocupe,
                nosotros tomaremos las
                cifras que contiene su documento y generaremos la letra automáticamente.
            </p>
            <p>
                <strong><span class="material-icons"
                              style="font-size: 18px; margin-right: 5px; color: var(--color-title);">verified</span>C&oacute;digo
                    postal:</strong> Debe
                introducir un mínimo de 5 d&iacute;gitos. Hecho
                esto,
                validaremos que
                es el perteneciente a la localidad que ha introducido.
            </p>
            <p><strong><span class="material-icons"
                             style="font-size: 18px; margin-right: 5px; color: var(--color-title);">verified</span>Contrase&ncaron;a
                    y
                    Confirmaci&oacute;n:</strong>
                Es uno de los registros que más
                problemas genera al
                usuairo. Le aconsejamos clicar en el icono para hacer visible lo que escriba.
            </p>
        </div>
    </div>

    <div class="info__ventana__footer">
        <p id="close" class="close">CERRAR</p>
    </div>
</dialog>
