<footer>
    <div class="container__footer">
        <div class="container__list__footer">
            <h3>Por qu&eacute; comprar</h3>
            <ul>
                <li>Premium</li>
                <li>C&oacute;mo comprar</li>
                <li>Formas de pago</li>
                <li>Gastos de env&iacute;o</li>
                <li>Cupones descuento</li>
                <li>Preguntas frecuentes</li>
            </ul>
        </div>
        <div class="container__list__footer">
            <h3>Qui&eacute;nes somos</h3>
            <ul>
                <li>Qui&eacute;nes somos</li>
                <li>Nuestras tiendas</li>
                <li>Condiciones de compra</li>
                <li>Macas</li>
                <li>Afiliados</li>
                <li>Centros educativos</li>
                <li>Aviso legal</li>
                <li>Privacidad</li>
            </ul>
        </div>
        <div class="container__list__footer">
            <h3>Contactar</h3>
            <ul>
                <li>Centro de soporte</li>
                <li>Contacto</li>
                <li>Devoluciones y garantías</li>
                <li>Opina y gana</li>
                <li>Publicidad</li>
                <li>Trabaja con nosotros</li>
                <li>Pol&iacute;tica de cookies</li>
            </ul>
        </div>
        <div class="container__list__footer">
            <h3>Comunidad</h3>
            <ul>
                <li><a><i class="fab fa-facebook fab__footer"></i></a></li>
                <li><a><i class="fab fa-twitter fab__footer"></i></a></li>
                <li><a><i class="fab fa-whatsapp fab__footer"></i></a></li>
                <li><a><i class="fab fa-instagram fab__footer"></i></a></li>
                <li><a><i class="fab fa-twitch fab__footer"></i></a></li>
                <li><a><i class="fab fa-youtube-square fab__footer"></i></a></li>
            </ul>
        </div> 
    </div>
    <div class="autor">
        <p>Manuel Guill&eacute;n Gallardo. Tienda Virtual (Proyecto DAW2). 18/01/2021</p>
    </div>

</footer>